name: C++ CI Matrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  packages: write
  contents: read

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libboost-system-dev libopencv-dev ffmpeg libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libwebp-dev pkg-config

    - name: Install Dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install cmake boost opencv ffmpeg webp pkg-config

    - name: Configure NuGet Cache (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name "GitHub" --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text
      shell: bash

    - name: Configure CMake (Ubuntu/macOS)
      if: matrix.os != 'windows-latest'
      run: >
        cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=Release
        -DMEDIA_COMPRESS_NET_BUILD_TESTS=ON
      env:
        PKG_CONFIG_PATH: "/opt/homebrew/lib/pkgconfig:/usr/local/lib/pkgconfig"

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      env:
        VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"
      run: >
        cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=Release
        -DMEDIA_COMPRESS_NET_BUILD_TESTS=ON
        -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
      shell: bash

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release --output-on-failure
